### ISSUE TITLE
Cannot convert a symbolic Tensor (switch_case/indexed_case/strided_slice:0) to a numpy array.

### ISSUE THREAD

**Issue by thomas-chia** [retoschiegg/meta-pseudo-labels#4]
Hello, when running the training function the program throws this error:

NotImplementedError: Cannot convert a symbolic Tensor (switch_case/indexed_case/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

I think it has something to do with the augmentation functions, but I am not entirely sure if it is due to the code or something else. Thank you for the help!

    (venv)  zzzzz@LAPTOP-XXXXXXXX:~/ARM/dev/mpl$ python src/main.py --data-dir data/cifar10 --config-name cifar10 --model-dir workdir/training --mpl-epochs 10000 --mpl-batch-size 64 --finetune-epochs 1000 --finetune-batch-size 512
    2021-06-26 21:26:20.086490: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
    2021-06-26 21:26:21.143558: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
    2021-06-26 21:26:21.456929: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:21.457338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
    pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
    coreClock: 1.35GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 245.91GiB/s
    2021-06-26 21:26:21.457520: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
    2021-06-26 21:26:21.461562: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
    2021-06-26 21:26:21.461738: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
    2021-06-26 21:26:21.462562: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
    2021-06-26 21:26:21.462871: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
    2021-06-26 21:26:21.465911: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
    2021-06-26 21:26:21.466621: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
    2021-06-26 21:26:21.466783: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
    2021-06-26 21:26:21.467844: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:21.468815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:21.469128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
    2021-06-26 21:26:21.471998: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
    2021-06-26 21:26:21.476350: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:21.476644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
    pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
    coreClock: 1.35GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 245.91GiB/s
    2021-06-26 21:26:21.477548: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:21.478934: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:21.479376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
    2021-06-26 21:26:21.479487: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
    2021-06-26 21:26:22.804455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
    2021-06-26 21:26:22.804514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
    2021-06-26 21:26:22.804525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
    2021-06-26 21:26:22.806813: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:22.807947: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:22.808257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1501] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
    2021-06-26 21:26:22.808968: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:923] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
    Your kernel may have been built without NUMA support.
    2021-06-26 21:26:22.809354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3937 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
    2021-06-26 21:26:22,816 - 9801 - train - INFO - Number of gpus found: 1
    WARNING:tensorflow:From /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:5043: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
    Instructions for updating:
    The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
    2021-06-26 21:26:24,062 - 9801 - tensorflow - WARNING - From /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:5043: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
    Instructions for updating:
    The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
    Traceback (most recent call last):
      File "src/main.py", line 185, in <module>
        main()  # pylint: disable=no-value-for-parameter
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "src/main.py", line 170, in main
        train_classifier(
      File "src/main.py", line 92, in train_classifier
        train_mpl(
      File "/home/ zzzzz/ARM/dev/mpl/src/train.py", line 251, in train_mpl
        unlabeled_dataset = get_unlabeled_train_ds(
      File "/home/ zzzzz/ARM/dev/mpl/src/dataset.py", line 52, in get_unlabeled_train_ds
        dataset = dataset.map(preprocess, num_parallel_calls=tf.data.experimental.AUTOTUNE)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1927, in map
        return ParallelMapDataset(
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4522, in __init__
        self._map_func = StructuredFunctionWrapper(
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3712, in __init__
        self._function = fn_factory()
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3134, in get_concrete_function
        graph_function = self._get_concrete_function_garbage_collected(
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3100, in _get_concrete_function_garbage_collected
        graph_function, _ = self._maybe_define_function(args, kwargs)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
        func_graph_module.func_graph_from_py_func(
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3687, in wrapped_fn
        ret = wrapper_helper(*args)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3617, in wrapper_helper
        ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
      File "/home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    NotImplementedError: in user code:
    
        /home/ zzzzz/ARM/dev/mpl/src/dataset.py:46 preprocess  *
            aug_image = augment_image(org_image)
        /home/ zzzzz/ARM/dev/mpl/src/dataset.py:87 augment_cifar10  *
            image_uint = rand_augment.distort(image_uint)
        /home/ zzzzz/ARM/dev/mpl/src/autoaugment.py:1022 distort  *
            branch_fns.append(
        /home/ zzzzz/ARM/dev/mpl/src/autoaugment.py:389 wrapped_rotate  *
            image = rotate(wrap(image), degrees=degrees)
        /home/ zzzzz/ARM/dev/mpl/src/autoaugment.py:551 wrap  *
            extended_channel = tf.ones([shape[0], shape[1], 1], image.dtype)
        /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
            return target(*args, **kwargs)
        /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:3212 ones
            output = _constant_if_small(one, shape, dtype, name)
        /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:2896 _constant_if_small
            if np.prod(shape) < 1000:
        <__array_function__ internals>:5 prod
    
        /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3051 prod
            return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
        /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86 _wrapreduction
            return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
        /home/ zzzzz/ARM/dev/mpl/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:867 __array__
            raise NotImplementedError(
    
        NotImplementedError: Cannot convert a symbolic Tensor (switch_case/indexed_case/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by retoschiegg** [comment]
I have just created the virtual environment as described in the README and I could not reproduce your error.
The error occurs indeed within the autoaugment.py which I copied from the [tensorflow/models repository](https://github.com/retoschiegg/meta-pseudo-labels/blob/master/src/autoaugment.py#L1).

What version of numpy and tensorflow do you use?
Here are the package versions of my current environment:

```
absl-py==0.13.0
appdirs==1.4.4
astroid==2.6.0
astunparse==1.6.3
atpublic==2.3
boto3==1.17.101
botocore==1.20.101
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.5
cfgv==3.3.0
chardet==4.0.0
click==7.1.2
colorama==0.4.4
commonmark==0.9.1
configobj==5.0.6
dagshub==0.1.6
decorator==4.4.2
dictdiffer==0.8.1
diskcache==5.2.1
distlib==0.3.2
distro==1.5.0
dpath==2.0.1
dulwich==0.20.23
dvc==2.1.0
filelock==3.0.12
flatten-dict==0.4.0
flufl.lock==3.2
fsspec==0.9.0
ftfy==6.0.3
funcy==1.16
future==0.18.2
gast==0.3.3
gitdb==4.0.7
GitPython==3.1.18
google-auth==1.32.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
gorilla==0.4.0
grandalf==0.6
grpcio==1.38.1
h5py==2.10.0
identify==2.2.10
idna==2.10
isort==5.9.1
jmespath==0.10.0
joblib==1.0.1
jsonpath-ng==1.5.2
Keras==2.4.3
Keras-Preprocessing==1.1.2
lazy-object-proxy==1.6.0
mailchecker==4.0.9
Markdown==3.3.4
mccabe==0.6.1
nanotime==0.5.2
networkx==2.5.1
nodeenv==1.6.0
numpy==1.18.5
oauthlib==3.1.1
opt-einsum==3.3.0
packaging==20.9
pathspec==0.8.1
phonenumbers==8.12.26
pkg-resources==0.0.0
ply==3.11
pre-commit==2.12.1
protobuf==3.17.3
psutil==5.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydot==1.4.2
pygit2==1.6.1
Pygments==2.9.0
pygtrie==2.3.2
pylint==2.8.2
pyparsing==2.4.7
python-benedict==0.24.0
python-dateutil==2.8.1
python-fsutil==0.5.0
python-slugify==5.0.2
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rich==10.4.0
rsa==4.7.2
ruamel.yaml==0.17.10
ruamel.yaml.clib==0.2.4
s3transfer==0.4.2
scikit-learn==0.24.2
scipy==1.7.0
shortuuid==1.0.1
shtab==1.3.6
six==1.16.0
smmap==4.0.0
tabulate==0.8.9
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.3.2
tensorflow-estimator==2.3.0
termcolor==1.1.0
text-unidecode==1.3
threadpoolctl==2.1.0
toml==0.10.2
tqdm==4.61.1
typing-extensions==3.10.0.0
urllib3==1.26.6
virtualenv==20.4.7
voluptuous==0.12.1
wcwidth==0.2.5
Werkzeug==2.0.1
wrapt==1.12.1
xmltodict==0.12.0
zc.lockfile==2.0
```

**Comment by thomas-chia** [comment]
Hi, thank you for the pip freeze list. I think it was something due to my WSL2 environment that made me use CUDA 11.0 and thus prohibited me from using TensorFlow 2.3. I ran a quick train with 20 epochs and the results are promising. Thank you for your time and help.
